<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
<caption><a href="/product/">Back To Home</a></caption><br><br>
<caption><a href="/product/view">Back To Product view</a></caption><br>
    <form action="" method="post">
    <label for="">Product Name:</label>
    <input type="text" name="name" id="name"><br><br>
    <label for="">Category Name:</label>
    <input type="text" name="cat_name" id="cat_name"><br><br>
    <label for="">Product Price:</label>
    <input type="text" name="price" id="price"><br><br>
    <label for="">Product Stock:</label>
    <input type="text" name="stock" id="stock"><br><br>
    <?php
    foreach ($edit_data['metafield'] as $a)
    {
        echo "label: <input type='text' name='label[]' placeholder=".$a['label']."><br><br>";
        echo "value: <input type='text' name='value[]' placeholder=".$a['value']."><br><br>";
    } 
    ?>
    <br>
    <?php
    foreach ($edit_data['variation'] as $a)
    {
        echo "Attribute Name: <input type='text' name='attr_name[]' placeholder=".$a['attr_name']."><br><br>";
        echo "Attribute value: <input type='text' name='attr_value[]' placeholder=".$a['attr_value']."><br><br>";
    } 
    ?>
    <input type="submit" value="Update">

    </form>


    
</body>
</html>