<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
   table {
      width: 700px;
      text-align: center;
      border: 1px solid #fff;
      border-spacing: 1px;
      font-family: 'Cairo', sans-serif;
      margin: auto;
   }

   caption {
      font-weight: bold;
   }

   table td {
      padding: 10px;
      background-color: #eee;
   }

   table th {
      background-color: #333;
      color: #fff;
      padding: 10px;
   }

   img {
      width: 90px;
      height: 90px;
   }

   .view,
   .delete {
      border: none;
      padding: 5px 10px;
      color: #fff;
      font-weight: bold;
   }

   .view {
      background-color: #03A9F4;
   }

   .delete {
      background-color: #E91E63;
   }

   .tablefoot {
      padding: 0;
      border-bottom: 3px solid #009688;
   }
   .overlay {
  position: fixed;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
  background: rgba(0, 0, 0, 0.7);
  transition: opacity 500ms;
  visibility: hidden;
  opacity: 0;
}
.overlay:target {
  visibility: visible;
  opacity: 1;
}

.popup {
  margin: 70px auto;
  padding: 20px;
  background: #fff;
  border-radius: 5px;
  width: 30%;
  position: relative;
  transition: all 5s ease-in-out;print_r($products->toArray()
}

.popup h2 {
  margin-top: 0;
  color: #333;
  font-family: Tahoma, Arial, sans-serif;
}
.popup .close {
  position: absolute;
  top: 20px;
  right: 30px;
  transition: all 200ms;
  font-size: 30px;
  font-weight: bold;
  text-decoration: none;
  color: #333;
}
.popup .content {
  max-height: 100%;
  overflow: auto;
}

@media screen and (max-width: 700px){
  .box{
    width: 70%;
  }
  .popup{
    width: 70%;
  }
}
</style>
</head>
<body>
<h2 style="margin-left: 40%;">Order Lists</h2>
<table id="myTable">
   <caption><a href="/product/view">view Products</a></caption>
   <caption><a href="/product/">add Products</a></caption>
   <caption><a href="/order/">add Order</a></caption>
   <form action="/order/view" method="POST">
                    <div class="col-2">
                        <select name="filter_status" id="filter_status" onchange="this.form.submit()">
                            <option value="choose">Choose By Status</option>
                            <option value="paid">Paid</option>
                            <option value="processing">Processing</option>
                            <option value="dispatched">Dispatched</option>
                            <option value="shipped">Shipped</option>
                            <option value="refunded">Refunded</option>
                        </select>

                    </div>

                    <div class="col-2">
                        <select name="filter_date" onchange="this.form.submit()">
                            <option value="choose">Choose By Date</option>
                            <option value="today">Today</option>
                            <option value="this_week">This Week</option>
                            <option value="this_month">This Month</option>
                            <option value="custom">Custom</option>
                        </select>
                    </div>
                </form>
    

   <thead>
      <tr>
         <th>Product Id</th>
         <th>Variations</th>
         <th>Customer</th>
         <th>Address</th>
         <th>Quantity</th>
         <th>Total Price</th>
         <th>Email</th>
         <th>contact</th>
         <th>Status</th>
         <th>Date</th>
      </tr>
   </thead>
   <tbody>
      <?php 
    //  $i =0 ;
      foreach ($order as $key) { ?>
         <tr>
            <td><?php echo $key['pro_name']; ?></td>
            <td><?php echo $key['variate']; ?></td>
            <td><?php echo $key['cust_name']; ?></td>
            <td><?php echo $key['address']; ?></td>
            <td><?php echo $key['quanti']; ?></td>
            <td><?php echo $key['Total_price']; ?></td>
            <td><?php echo $key['email']; ?></td>
            <td><?php echo $key['contact']; ?></td>
            <td><form action="/order/view" method="POST">
                        <input type="hidden" name="order_id" value="<?php echo $key['_id'];?>">
                        <select name="status" id="status" onchange="this.form.submit()">
                        <option value="choose">Choose</option>
                          <option value="paid">Paid</option>
                          <option value="processing">Processing</option>
                          <option value="dispatched">Dispatched</option>
                          <option value="shipped">Shipped</option>
                          <option value="refunded">Refunded</option>
                        </select>
                        </form></td>
                        <td><?php echo $key['date']; ?></td>
            
              <?php } ?>
    
         </tr>
   </tbody></form>
</table>
	</body>
</html>